### ISSUE TITLE
It detects the wrong GPU

### ISSUE THREAD

**Issue by GOKOP** [sam-barr/paleofetch#16]
I've just given this program a try and a thing I've noticed is that although I'm using a GTX 960, paleofetch says I'm using "Intel Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]". This looks like some generic guess on what my integrated graphics is, but that's not the card I use.

**Comment by dwzg** [comment]
GPU detection is currently very simple and just looks for the string "Graphics" in the PCI device name, which probably only works for integrated Intel GPUs.

How is your GTX presenting itself when you execute "lscpi" in the terminal?
Maybe simply adding a check for "Nvidia" in the device name is a solution.

**Comment by ss7m** [comment]
My solution for finding the graphics card was very rudimentary; I couldn't immediately finding anything in libpci that tells you its a graphics card, but I didn't look terribly hard if I'm being honest.

**Comment by GOKOP** [comment]
> How is your GTX presenting itself when you execute "lscpi" in the terminal?
```
$ lspci | grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GM206 [GeForce GTX 960] (rev a1)
```

> Maybe simply adding a check for "Nvidia" in the device name is a solution.

I think that would also have to include "AMD", but then someone could _have_ a dedicated card but still use the integrated one for some reason.

**Comment by ss7m** [comment]
I need to look if there's something in libpci that'll tell you that something is a VGA compatible controller. It might be worth looking through the source code for lspci at some point.

**Comment by ss7m** [comment]
I think I figured it out, the next commit should fix this issue

**Comment by ss7m** [comment]
@GOKOP Try the latest commit, let me know if that works for you

**Comment by GOKOP** [comment]
Nope, still the same

**Comment by GOKOP** [comment]
Oh it actually works, had to run with `--recache`.
Seems correct, "NVIDIA  GM206 [GeForce GTX 960]"
