### ISSUE TITLE
Uptime broken when under 1 minute

### ISSUE THREAD

**Issue by dwzg** [sam-barr/paleofetch#28]
Right after booting the uptime is broken until 1 minute is reached.
![uptime_bug](https://user-images.githubusercontent.com/50058606/80122450-dba30b80-858d-11ea-9b05-a4cd84457d67.png)

**Comment by ss7m** [comment]
Latest commit should fix this

**Comment by dwzg** [comment]
Can confirm that the bug is fixed.

**Comment by allisio** [comment]
Should we perhaps report seconds instead of always reporting minutes even when they're zero?

**Comment by ss7m** [comment]
I think I'd actually prefer 0 mins to reporting seconds; I don't think its worth the hassle (not that it'd necessarily be that big a hassle) for what amounts to a tiny edge case
