### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by GOKOP** [sam-barr/paleofetch#33]
Built at commit be825d7
It starts printing but segfaults when it's supposed to print i-dont-remember-what. (probably distro name)
```
$ ./paleofetch 
                  -`                    gokop@demunarch
                 .o+`                   ---------------
[1]    13866 segmentation fault  ./paleofetch
```

**Comment by ss7m** [comment]
What operating system are you on? Do you not have an /etc/os-release file? In any case, error handling should be added for `get_os`

**Comment by ss7m** [comment]
In any case, try the latest commit and tell me what the results are.

**Comment by GOKOP** [comment]
Artix Linux. But it seems like all it took to fix was to run it with `--recache`. It may be worth attention tho that cache from older builds may break the program. Anyway I'm closing because my issue is solved
