### ISSUE TITLE
Error of failed request: BadWindow

### ISSUE THREAD

**Issue by adityaarun1** [sam-barr/paleofetch#38]
Hi,
I get the following error when running `paleofetch`. I am currently on the latest commit.

![Screenshot from 2020-04-24 10-06-54](https://user-images.githubusercontent.com/6547096/80175522-6712b000-8613-11ea-877c-465622ee3d06.png)

[Edit]
The issue occurs in the `get_terminal` call. Commenting out that line resolves the issue. I am using `gnome-terminal` if that helps.

**Comment by allisio** [comment]
Hello. Could you show the results of running `xprop -root _NET_ACTIVE_WINDOW` on your system?

**Comment by adityaarun1** [comment]
Here you go.
![Screenshot from 2020-04-24 13-07-23](https://user-images.githubusercontent.com/6547096/80187136-bdd8b380-862c-11ea-8706-d53124933a61.png)

**Comment by allisio** [comment]
Well, that's definitely the problem; that request shouldn't be returning the root window. 

Doing a search for `gnome-terminal _NET_ACTIVE_WINDOW` returns plenty of results wherein people use/recommend this feature to get the controlling terminal, so either there's been a recent change to GNOME (that stops `gnome-terminal` instances from being mapped?!) or something unorthodox about your configuration.

I'm afraid I don't know how best to proceed in resolving this issue. :/

**Edit**: Other than resorting to the fallback if `window` is 0 after the property request, which would in fact return exactly the right value in this case.

**Comment by adityaarun1** [comment]
Oh, sorry to hear that.

FWIW I am using `wayland` instead of `X`. Not sure if this is that unorthodox or the cause of the problem. Also, `neofetch` successfully shows my terminal.

**Comment by allisio** [comment]
FWIW, from the very top of the README:

> Currently only supports Linux and **Xorg**.

`neofetch` shows your terminal by reading the `TERM` environment variable, which is currently what `paleofetch` resorts to doing if it can't open an X display. The fact that you hit this snag means that it *was* able to open one, so presumably you're actually using XWayland.

In any case, resolving this particular issue now appears to be pretty straightforward.

**Comment by adityaarun1** [comment]
Right, my bad. I'll try to make this script generalizable to `wayland` too. Thanks.
