### ISSUE TITLE
unable to open product name file

### ISSUE THREAD

**Issue by Titaniumtown** [sam-barr/paleofetch#55]
When I run paleofetch on my raspberry pi 4, running arch linux arm, I get the error:
paleofetch: unable to open product name file

**Comment by ss7m** [comment]
Can you tell me if either of the files `sys/firmware/devicetree/base/model` or `/tmp/sysinfo/model` exist on your system? 

In the meantime, removing the get_host line from `config.h` will stop it from crashing.

**Comment by Titaniumtown** [comment]
/sys/firmware/devicetree/base/model exists, but /tmp/sysinfo/model doesn't

**Comment by Titaniumtown** [comment]
cat /sys/firmware/devicetree/base/model:
Raspberry Pi 4 Model B Rev 1.1

**Comment by ss7m** [comment]
I suppose that can be added as a fallback then.

**Comment by ss7m** [comment]
Latest commit should add the devicetree file as a fallback

**Comment by Titaniumtown** [comment]
It works now, thanks!
