### ISSUE TITLE
Ascii art usage

### ISSUE THREAD

**Issue by Titaniumtown** [sam-barr/paleofetch#58]
Do we have to make our own ascii art for each OS or can we just copy it from https://github.com/dylanaraps/neofetch/blob/master/neofetch

Is it a legal thing?

**Comment by ss7m** [comment]
Both paleofetch and neofetch are open source and licensed under MIT, so I don't think copying them would be a legal issue. If I interpret the wording of the license correctly, if we used enough of them we'd have to include their copy of the MIT license in the source code. At the very least if you copy from neofetch you should mention it in a comment.

**Comment by Titaniumtown** [comment]
Oh ok, I just wanted to make sure! :)
