### ISSUE TITLE
What directory does Paleofetch install under?

### ISSUE THREAD

**Issue by jake-87** [sam-barr/paleofetch#68]
I think it's ~/bin/paleofetch, am I right or wrong?

Thanks in advance.

**Comment by Titaniumtown** [comment]
depends how you install it.

**Comment by jake-87** [comment]
1st: Thanks for the reply in under a minute
2nd: If I wanted to read a file in the directory where the c file is running, could I just do

`example = fopen("~/example.txt","r")`

**Comment by Titaniumtown** [comment]
idk much C, so google is your best bet. You should close this issue.

**Comment by jake-87** [comment]
Ok, thanks.
