### ISSUE TITLE
[enhancement] Should paleofetch detect the user's window manager?

### ISSUE THREAD

**Issue by allisio** [sam-barr/paleofetch#8]
I have a patch ready to go that supports [EWMH-compliant](https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints#List_of_window_managers_that_support_Extended_Window_Manager_Hints) window managers, but I wanna make sure it's within the spirit of the project before requesting the pull. It's only ~20 lines and still blazing-fast, but it could spell the beginning of "feature creep" since naturally we'd also want to get the DE if applicable, and that could be a can of worms.

**Comment by ss7m** [comment]
I don't think that's something I'm looking to add right now, but if I get around to implementing some sort of configurability in the future that'll definitely be something to put in.
