### ISSUE TITLE
Add terminal output

### ISSUE THREAD

**Issue by ss7m** [sam-barr/paleofetch#9]
Currently paleofetch does not detect what terminal you're using. Note that $TERM is not necessarily a reliable way to get this information- I use alacritty but my $TERM is set to xterm-256color.

Neofetch examines the parent process to get this; that might be a good approach to take.

**Comment by allisio** [comment]
I think we can actually do one better than `neofetch` here. Parsing `/proc/$PPID/comm` is nice and easy, but it returns the name of the terminal's *executable*, which isn't quite the same as the name of the terminal emulator itself. I could repurpose the code for getting the window manager to instead get the name of the active window. I don't know under what circumstances this would fail to return the correct value, but I think it would work in the vast majority of cases.

**Comment by ss7m** [comment]
I just quickly added reading $TERM for sake of completeness, but this sounds like it could lead to more accurate results.

**Comment by dwzg** [comment]
> I think we can actually do one better than `neofetch` here. Parsing `/proc/$PPID/comm` is nice and easy, but it returns the name of the terminal's _executable_, which isn't quite the same as the name of the terminal emulator itself. I could repurpose the code for getting the window manager to instead get the name of the active window. I don't know under what circumstances this would fail to return the correct value, but I think it would work in the vast majority of cases.

Don't some terminals show the name of the currently executed program in the window title?(assuming this is equivalent to the name of the active window)

**Comment by allisio** [comment]
> Don't some terminals show the name of the currently executed program in the window title?(assuming this is equivalent to the name of the active window)

Some terminals do indeed do that, but thankfully it's not the same thing.

**Edit**: Sorry; where I said "name", I meant "class". You're right that using `WM_NAME` would be cause for concern, but I use `WM_CLASS` in the relevant pull request.

**Comment by matthewfritsch** [comment]
It looks like `neofetch` uses the current application in the terminal name. I'm on Manjaro KDE: 
When I use `neofetch` on kitty, my `$TERM` is "xterm-kitty" and it lists my Terminal as "kitty". 
When I use `neofetch` on Konsole, my `$TERM` is "xterm-256color" and it lists my Terminal as "konsole". 
When I use `neofetch` on alacritty, my `$TERM` is "alacritty" and it lists my Terminal as "alacritty". 
@sam-barr your $TERM stays constant as "xterm-256color" in all terminals? Just double checking that $TERM doesn't associate with a particular terminal. If my scenario _is_ normal, then maybe you have a "Default Application" or similar set somewhere on your DDE?

**Comment by ss7m** [comment]
I only use alacritty, which I've specifically configured to set $TERM to xterm-256color. Currently I'm satisfied with the solution that @allisio wrote, and don't think that reading $TERM is the correct solution.

**Comment by matthewfritsch** [comment]
Ah, missed that post. My mistake, got it.
